apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
template:
  metadata:
    labels:
      app: gateway
    spec:
      containers:
        - name: gateway
          image: allant102/gateway:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: gateway-configmap
            - secretRef:
                name: gateway-secret
