# Use a Python base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt \
    && apt-get -y update \ 
    && apt-get -y upgrade \
    && apt-get install -y ffmpeg

# Copy the Flask application code to the working directory
COPY . .

CMD ["python3", "consumer.py"]